on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_run:
    workflows: ["Run Tests"]
    types: 
      - completed
      - requested

